baseURL = 'https://Skyth3r.github.io'
languageCode = 'en-us'
title = 'Akash Goswami'
theme = ['hugo-cloak-email', 'digitalgarden']
enableRobotsTXT = true

[Params]
  description = "Akash Goswami's personal website"
  images = ['https://raw.githubusercontent.com/skyth3r/skyth3r.github.io/master/assets/akashgoswami.png']

[Params.newsletter]
  title = ""
  description = "Recieve new articles directly in your mailbox!"
  provider = "buttondown"
  path = "https://buttondown.email/api/emails/embed-subscribe/akashgoswami"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Notes'
  url = '/notes'
  weight = 4
[[menu.main]]
  name = 'Tools'
  url = '/tools'
  weight = 5
[[menu.main]]
  name = 'Now'
  url = '/now'
  weight = 6
[[menu.main]]
  name = 'Tags'
  url = '/tags'
  weight = 7
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 8
[[menu.main]]
  name = 'akashgoswami.dev'
  url = 'https://akashgoswami.dev'
  weight = 9

[[menu.social]]
  name = 'Mastodon'
  url = 'https://hachyderm.io/@akashgoswami'
  weight = 1
[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/akashgoswami_'
  weight = 2
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Skyth3r'
  weight = 3
[[menu.social]]
  name = 'Polywork'
  url = 'https://timeline.akashgoswami.com'
  weight = 4
[[menu.social]]
  name = 'Email'
  url = 'mailto:akash@akashgoswami.com'
  weight = 5
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 6

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[outputs]
    section = ["HTML","RSS", "JSON"]