name: update-now

on:
  schedule:
    - cron: '50 1 * * *'
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get branch
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: run script
        run: |
          cd ${GITHUB_WORKSPACE}/scripts
          ./automate-now
      - name: deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add . 
          git commit -m "üç± Dynamic now page update"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git